steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/csci-5409-cloud-389821/docker-1/k8:docker1'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/csci-5409-cloud-389821/docker-1/k8:docker1'
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        terraform init
        terraform validate
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=./csci-5409-cloud-389821-576de4354b9e.json'
      - 'GOOGLE_PROJECT_ID=csci-5409-cloud-389821'
      - 'GOOGLE_REGION=us-central1'

images:
  - 'us-central1-docker.pkg.dev/csci-5409-cloud-389821/docker-1/k8:docker1'
