steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/csci-5409-cloud-389821/docker-2/k8:docker2'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/csci-5409-cloud-389821/docker-2/k8:docker2'

images:
  - 'us-central1-docker.pkg.dev/csci-5409-cloud-389821/docker-2/k8:docker2'