apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-1
  namespace: default
  labels:
    app: docker-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-1
  template:
    metadata:
      labels:
        app: docker-1
    spec:
      containers:
        - name: docker-1
          image: us-central1-docker.pkg.dev/csci-5409-cloud-389821/docker-1/k8@sha256:0716535bcd2148d65dc30d0423def033c48674d21013d157a63aebab8f130d88
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: my-pvc
